# GitHub Pages Configuration
title: CitizenAI Documentation
description: Intelligent Citizen Engagement Platform - Empowering citizens through AI-driven engagement and real-time analytics
baseurl: "/Citizen-AI"
url: "https://AkhileshMalthi.github.io"

# Theme - using a more reliable theme for GitHub Pages
remote_theme: pages-themes/primer@v0.6.0

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-remote-theme

# Markdown settings
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true

# Collections
collections:
  docs:
    output: true
    permalink: /:collection/:name/

# Defaults
defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
  - scope:
      path: ""
      type: "docs"
    values:
      layout: "default"

# Navigation
header_pages:
  - index.md
  - SETUP.md
  - API_REFERENCE.md
  - BUILD_PROGRESS.md
  - DEPLOYMENT.md

# SEO
lang: en-US
author: 
  name: CitizenAI Team
  email: your-email@example.com

# Social
github_username: your-username
twitter_username: your-twitter

# Google Analytics (optional)
# google_analytics: UA-NNNNNNNN-N

# Exclude from processing
exclude:
  - README_new.md
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

# Include
include:
  - _pages

# Site settings
timezone: America/New_York
encoding: utf-8

# Build settings
safe: true
incremental: false
profile: false
strict_front_matter: false
